### ISSUE TITLE
Tool doesn't load in internet explorer version 11

### ISSUE THREAD

**Issue by pjoice** [flexion/hud-disaster-data#12]
Screenshot below. I'm running IE 11 version 11.0.9600.18665CO

![image](https://cloud.githubusercontent.com/assets/28014307/26798061/d0aadaaa-49f4-11e7-95f8-ca8230144de7.png)

**Comment by davehannon** [comment]
We added:
import es6Promise from 'es6-promise'
es6Promise.polyfill()

before loading vuex to fix

**Comment by piascikj** [comment]
@pjoice What are the current issues with IE?

**Comment by pjoice** [comment]
Source of problem seems to be something that happened after IE update version 11.0.42. Related to font awesome.

**Comment by pjoice** [comment]
Problem identified: older versions of IE 11 do not (by default) allow web fonts to be downloaded. Some users (specifically me at HUD) cannot modify browser security settings to fix.

Solution ... ?
