### ISSUE TITLE
Guided experience testing

### ISSUE THREAD

**Issue by pjoice** [flexion/hud-disaster-data#15]
This is as of 10:45 central on 6/14, after the sprint review demo. Comments relate to guided experience.

On the first modal dialogue:
1. Title should be "Search for a disaster"
2. There's still a typo. "FL). should be "FL").
3. The final paragraph provides two links. The first is the hyperlinked word "here". The second is the link itself. Do we want to have both? I would think that the ideal solution would be: "Click here: https://www.fema.gov/disasters" (just show the url as a link). But I'm happy to defer to others.
4. When the user clicks on that link, it should open in a new tab. Currently it navigates away from the tool, which essentially forces the user to restart the guided experience.

![image](https://user-images.githubusercontent.com/28014307/27141785-bf7cdaca-50ee-11e7-94e7-66b4a10892ff.png)

Second modal dialogue.
1. Title should be "Select a disaster"

Third modal dialogue.
1. Title should be "Disaster selected"
2. I think this dialogue should be split in two. This dialogue should end after "First, let's try exporting the data."
3. Instead of pointing to the "Export" button, this bubble would point to the window where the disaster has been added.
4. Export button will be grayed out. User clicks "Next" to advance.

New (fourth) modal dialogue.
1. Title should be "Export data".
2. Bubble should point to the Export button, which is now activated.
3. Text should read "To get household level data for the disaster selected, click the export button. Your computer will download a .csv formatted file."

Fifth modal dialogue (currently fourth. adding a new disaster)
1. Title should be "Add to your list".

Sixth modal dialogue (currently fifth) 
1. Title should be "Select another disaster".
2. Typo: "Select additional states..." should be "Select additional disasters..."

Seventh modal dialogue (currently sixth)
1. Title should be "Name and save your list"
2. Error message is showing. "You have encountered... try again" should only appear if the user tries to advance without naming and saving. (note: this issue seemed to disappear as I was experimenting. Perhaps someone already fixed it.)

Eighth modal dialogue
1. Title should be "Remove from list"

Ninth modal dialogue
1. Title should be "Clear list"

Tenth modal dialogue
1. Title should be "Select a previously saved list"

Eleventh modal dialogue
1. Title should be "Delete previously saved list"
2. Add text "Warning: this will actually delete the list. If you do not want to delete a list, click Next"

Final dialogue:
1. Title "Complete"
2. Text: "Congratulations, you have completed the guided experience. Click here (link: FAQ) if you have additional questions."

**Comment by piascikj** [comment]
https://docs.google.com/document/d/1-TYi3oRRYmG1AqoE-2QxWLJnv7Aho9vpfspYHnpPDUw/edit?ts=59416fc2

**Comment by davehannon** [comment]
Paul -  is this ready to be closed?

**Comment by pjoice** [comment]
Almost!! Just a few minor things.

On the first dialogue, for "FL" : the second parenthesis is formatted different from the others.

On the third dialogue (Disaster selected), change "... now listed in the export area..." to "...now listed in the "Selected disasters area"... ". That is the header we want to give to this component so we should use that phrase here.

On the fourth dialogue (the one that starts "First, let's try exporting the data" and points to the export button, three things: 1. Change the title to Export data. 2. Delete the first sentence (So it should start "To get household level data..."). 3. Add a period at the very end.

On the fifth dialogue ("Add to your list") : we have the same parenthesis formatting issue for "CA". Also add a period at the very end.

On the "Name and save your list" dialogue, change "search list" to "Selected disaster list". Add a period at the end.

On the "Select a previously saved list" dialogue, when I select from the list, that list should populate below but currently does not. (this appears to be a problem outside the guided experience as well).

**Comment by pjoice** [comment]
A couple more:

Clear list dialogue: add a period to final sentence. Same for the next two dialogues (select/delete a saved list).

Also on the delete list dialogue, please add: "Warning: this will actually delete the list. If you do not want to delete a list, click Next."

After that, we're done on this! Nice work!

**Comment by davehannon** [comment]
Paul - 

You didn't ask for this, but would you like the warning to look like this:
![image](https://user-images.githubusercontent.com/2071581/27179298-911fde20-5193-11e7-858b-dce781bb3d66.png)

or this:
![image](https://user-images.githubusercontent.com/2071581/27179353-d1f551fa-5193-11e7-8310-21a37c92b196.png)
