### ISSUE TITLE
Smallest breakpoint doesn't work

### ISSUE THREAD

**Issue by waldoj** [flexion/hud-disaster-data#19]
When reducing the size of the browser to the smallest breakpoint, the divs overlap, rendering the site useless.

![overlap](https://user-images.githubusercontent.com/656758/27442564-95f1acb6-573e-11e7-98e0-0a884958dad3.png)

Looks like some tweaking is necessary.

**Comment by davehannon** [comment]
@waldoj - I believe this is done, correct?

**Comment by waldoj** [comment]
Kind of. The specific above overlay isn't happening anymore, but the smallest breakpoint still has a layering problem, obscuring all but the top ~10 pixels of the "Export" button.

![export](https://user-images.githubusercontent.com/656758/27873401-f7a7f3ee-6179-11e7-89fd-00c38a06b877.png)

It's not clear to me whether this is properly regarded as a continuation of this issue, or if it instead warrants a new one.
