### ISSUE TITLE
Comments not working in npm on windows

### ISSUE THREAD

**Issue by bryanmcfadden** [flexion/hud-disaster-data#20]
When running npm run dev I receive this error:

$ npm run dev

> hud-disaster-data@1.0.0 dev D:\_dev\hud-disaster-data
> ### Run the client side hot reloading dev server
    node build/dev-server.js

'###' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                                                                    node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! hud-disaster-data@1.0.0 dev: `### Run the client side hot reloading dev                                                                     server
npm ERR!     node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hud-disaster-data@1.0.0 dev script '### Run the client si                                                                    de hot reloading dev server
npm ERR!     node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hud-disaster-data pac                                                                    kage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ### Run the client side hot reloading dev server
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hud-disaster-data
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hud-disaster-data
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\_dev\hud-disaster-data\npm-debug.log

**Comment by piascikj** [comment]
Comments were replaced with echo.
