### ISSUE TITLE
Misleading tour error presented to user

### ISSUE THREAD

**Issue by bryanmcfadden** [flexion/hud-disaster-data#31]
The error shown on the first step is misleading. please follow the steps below to view:

1. Click the "Guide Me" button
2. Type "4272" in the disaster search input.
3. Click the "Next" button in the tour dialog.

You are then presented with this error which is incorrect:

![image](https://user-images.githubusercontent.com/16689692/27659385-455f00e0-5c21-11e7-9119-794fba7a4f66.png)

The error says I typed an invalid disaster ID, when in fact I typed a correct one. 
(which is still in the input)
I would recommend changing the dialog so it covers both the invalid disaster ID and the failure to execute and search for disasters as well as instructions that the user must click the magnifying glass to execute the search.

**Comment by thegoldentoilet** [comment]
Fixed in sprint-11
