### ISSUE TITLE
Tour is invisible to screen readers

### ISSUE THREAD

**Issue by waldoj** [flexion/hud-disaster-data#34]
Using the tour with a macOS's Voiceover enabled results in an experience that is no different than using the site without the tour. The divs that contain the explanatory text is never focused, so the text is never read. A non-sighted person using the site would conclude that the "Guide Me" button does nothing.

**Comment by waldoj** [comment]
The best option that I'm aware of is to have the “Guide Me” button trigger the appending of `aria-description` elements to each input box, with those elements containing the same text that’s in the overlays now. When the “Export” button is selected, that triggers the removal of those elements, so that subsequent uses of the form aren’t annoyingly verbose.

I haven't tried this, but I speculate that it would solve the problem.

**Comment by davehannon** [comment]
Waldo - where would you say this is by now?

**Comment by waldoj** [comment]
Looks great! (Or, rather, _sounds_ great.) 👍
