### ISSUE TITLE
Pressing 'enter/return' on Next button in tour doesn't advance to next step.

### ISSUE THREAD

**Issue by piascikj** [flexion/hud-disaster-data#36]

**Comment by piascikj** [comment]
[Advance tour on Next enter. · flexion/hud-disaster-data@c80f27d](https://github.com/flexion/hud-disaster-data/commit/c80f27def8200666da52b83e3bb865794f5c2374)

**Comment by davehannon** [comment]
I believe this is done, right?

**Comment by piascikj** [comment]
yes
