### ISSUE TITLE
Make saved search names visually distinct in dialog boxes

### ISSUE THREAD

**Issue by waldoj** [flexion/hud-disaster-data#37]
Not all dialog boxes make the names of saved searches visually distinct, which could yield confusing messages for users, who may not understand that they're seeing the name of the search. For example:

![confirmation](https://user-images.githubusercontent.com/656758/28125368-680f3528-66f4-11e7-9d64-bb064da2f322.png)

On the other hand, the confirmation step for deleting a saved search handles this properly, by wrapping the name of the save search in quotation marks.

![delete](https://user-images.githubusercontent.com/656758/28125321-4411a1b0-66f4-11e7-96d0-716a05872e75.png)

We need to ensure that each use of a saved search name is offset visually, to avoid such confusion.

**Comment by davehannon** [comment]
This should be fixed.
