### ISSUE TITLE
Disaster input not clearing value on event actions

### ISSUE THREAD

**Issue by bryanmcfadden** [flexion/hud-disaster-data#43]
The disaster input located in the report parameters does not clear as expected.
To reproduce the error, please follow these steps:

Step 1: 
Select the state of texas

![image](https://user-images.githubusercontent.com/16689692/28848440-ee8d5084-76e0-11e7-8321-a8a704868f99.png)

Step 2: 
Select City for the Geographical Level

![image](https://user-images.githubusercontent.com/16689692/28848462-fe09e284-76e0-11e7-930c-b2842f4f0069.png)

Step 3: 
Add the cities Houston and Fort Worth

![image](https://user-images.githubusercontent.com/16689692/28848471-0fd2dc0a-76e1-11e7-94e5-ddec7bfeb565.png)

Step 4: 
Type or select the disaster DR-4272-TX in the disasters search input. 
Then click the Add button.

![image](https://user-images.githubusercontent.com/16689692/28848488-1f0adce0-76e1-11e7-937f-5fe8b7ffa226.png)

The disaster typed or selected in the input remains after the it has been added to the list. 
(It should clear the input when added to the list)

It also remains when you select the clear button or change the state selection.
(it should be cleared then as well)

![image](https://user-images.githubusercontent.com/16689692/28848501-2983b1ce-76e1-11e7-9fd8-878c932823de.png)

**Comment by thegoldentoilet** [comment]
This has been fixed.
