### ISSUE TITLE
Report parameters do not reset

### ISSUE THREAD

**Issue by bryanmcfadden** [flexion/hud-disaster-data#44]
With the report parameters having based on hierarchy, when the geographical level is changed, the values selected within the sub-list must clear.

To create the error, follow these steps:

Step 1:
Type or select the state of Texas

![image](https://user-images.githubusercontent.com/16689692/28849367-bc58d094-76e4-11e7-9865-07a4d22ad30d.png)

Step 2:
Select City as the geographical level

![image](https://user-images.githubusercontent.com/16689692/28849458-1440e044-76e5-11e7-8fd7-e72808f22cde.png)

Step 3:
Add Houston and San Antonio as sub-list cities

![image](https://user-images.githubusercontent.com/16689692/28849483-32876078-76e5-11e7-8b10-d27cf138c473.png)

Step 4:
Change the geographical level to County

![image](https://user-images.githubusercontent.com/16689692/28849522-5f85b96c-76e5-11e7-8a27-c2470b9bfbda.png)

The geographical level changed to County in the title, however, the selected cities still remain as values in the sub-list and title. (These should now be cleared since we are working with counties)

**Comment by thegoldentoilet** [comment]
Cannot reproduce
