### ISSUE TITLE
City locales not loading on geographic level change

### ISSUE THREAD

**Issue by bryanmcfadden** [flexion/hud-disaster-data#45]
The city locales are not loading when the state and geographic level are changed. 
** This only occurs when the Geographic Level is reset.
 
In order to reproduce the error, follow these steps:

Step 1:
Reset all inputs within the report parameters

![image](https://user-images.githubusercontent.com/16689692/28878485-6a982956-776d-11e7-8a61-7acf23768a7b.png)

Step 2:
Enter or select the state of Wisconsin

![image](https://user-images.githubusercontent.com/16689692/28878605-c3461b12-776d-11e7-8fed-0de95e4f0a2b.png)

Step 3:
Select City from the Geographic Level dropdown.

![image](https://user-images.githubusercontent.com/16689692/28878638-ddddbb24-776d-11e7-97de-562081ca727f.png)

ERROR:
No cities are available for selection or search within the locale area located under the Geographic Level. This seems to be an error given the fact that state specific disasters are loaded in the next input (Disasters).

![image](https://user-images.githubusercontent.com/16689692/28878722-16ef4ca2-776e-11e7-972e-fbcb00a093f8.png)

**Comment by thegoldentoilet** [comment]
fixed in sprint-15
