### ISSUE TITLE
Report creation date not accurate/updating

### ISSUE THREAD

**Issue by bryanmcfadden** [flexion/hud-disaster-data#52]
The creation date is not accurate and does not update when generating reports. 

**Report Accuracy**
Example:
Step 1. Open Reporting page in application.
Step 2: Select a state from the state selector. (Alaska)
Step 3: Wait at least 1-2min before generating report.
Result: The generated report will have the time of initial page load (see image below)

**Report Date Not Updating**
Step 4: Select another state from the state selector. (Alabama)
Step 5: Wait at least another 1-2min before generating report.
Result: The generated report will have the time time of initial page load....not updating as it should.

![image](https://user-images.githubusercontent.com/16689692/29220025-d45399cc-7e87-11e7-8589-a58949c3f317.png)

**Comment by thegoldentoilet** [comment]
fixed in sprint-15
