### ISSUE TITLE
Report data does not clear on page exit

### ISSUE THREAD

**Issue by bryanmcfadden** [flexion/hud-disaster-data#59]
When navigating from the report page and then later returning, some report data remains. This data should be cleared upon exit or navigation change.

Follow these steps to recreate the issue:
Step 1: Select Wisconsin in the state selector
Step 2: Select county for the geographic level
Step 3: Add the locale "Dane(County)" to the locale list
Step 4: Click the create report button

The report is generated as seen below:

![image](https://user-images.githubusercontent.com/16689692/29378428-07341dd6-828d-11e7-8eab-7d0aa69906dc.png)

Step 5: Navigate to the Data Export page using the main menu
Step 6: Search for a disaster in the search disaster input
Step 7: Navigate to the Reports page using the main menu 

The page will look like this:

![image](https://user-images.githubusercontent.com/16689692/29378525-5eb5d932-828d-11e7-8fd1-68e869d443c0.png)

Result:

The geographic level is not cleared and disabled
The locales list is not cleared
The created on date is empty and visible
The export report button is active
The report body with values is displayed (should be set to default)

**Comment by thegoldentoilet** [comment]
fixed in sprint-16
