### ISSUE TITLE
Does URL need to be cleared when clearing report parameters?

### ISSUE THREAD

**Issue by bryanmcfadden** [flexion/hud-disaster-data#65]
When clicking the "Clear" button on the report parameters sidebar, the values from the previous search still remain. Should these be cleared as well? Even after the report has been generated? (URL parameters are there to bookmark the report parameters)

To create the issue, follow these steps:

Step 1:  Enter or select the state "Texas" in the state selector.

![image](https://user-images.githubusercontent.com/16689692/29638773-4d1a7b8a-8826-11e7-8dfc-71bbf51a6aae.png)

Step 2:  Select "City" from the Geographical Level drop-down

![image](https://user-images.githubusercontent.com/16689692/29638810-6eaf5752-8826-11e7-8499-65776c3916ea.png)

Step 3:  Add the cities "Houston" and "Friendswood" to the locale list

![image](https://user-images.githubusercontent.com/16689692/29638844-93af29c4-8826-11e7-9ebf-2d3ef1ce4a2f.png)

Step 4:  Add the disaster "DR-4272-TX" to the disaster list

![image](https://user-images.githubusercontent.com/16689692/29638890-bd6eab68-8826-11e7-8873-2263d3140ce6.png)

Step 5:  Create the report
(notice the URL parameters are present after generating a report)

![image](https://user-images.githubusercontent.com/16689692/29638914-d908a98c-8826-11e7-818e-3cb6ac194c83.png)

Step 6:  Click the "Clear" button in the report parameters sidebar and click "OK" to the confirmation popup

![image](https://user-images.githubusercontent.com/16689692/29638979-1dbc975a-8827-11e7-83c3-2d89550054e2.png)

The report parameters have cleared. (The URL values are still present at this point) 

![image](https://user-images.githubusercontent.com/16689692/29639024-43b985d0-8827-11e7-9593-0d621669338c.png)

Step 7: Refresh the browser page

![image](https://user-images.githubusercontent.com/16689692/29639077-7b9e4d96-8827-11e7-9ade-4095c12aa9f5.png)

Result: The report is no longer visible and the report parameters are set to the URL values.
Is this the preferred functionality?

**Comment by pjoice** [comment]
I have one foot out the door... but yes, I think that functionality is appropriate.

The only other reasonable option would be that when the user selects "clear" it clears everything: selection pane, report contents, and url. That might be better, but I don't think it's necessary. It's probably not practical to attempt to change it at this point.

**Comment by davehannon** [comment]
fixed
