### ISSUE TITLE
 abstract this so that the navbar fixed styles are not placed here? 

### ISSUE THREAD

**Issue by davehannon** [flexion/hud-disaster-data#73]
Issue opened with imdone.io from code comment on [6444247](https://github.com/flexion/hud-disaster-data/commit/64442473d97a502dc4e1349fdedc41f19a04133e)

TODO  abstract this so that the navbar fixed styles are not placed here? id:0

----

https://github.com/flexion/hud-disaster-data/blob/64442473d97a502dc4e1349fdedc41f19a04133e/app/public/assets/_scss/01-vendors/bootstrap/_dropdowns.scss#L181-L186

**Comment by piascikj** [comment]
In dependency
