### ISSUE TITLE
 Rename `$input-border-radius` to `$input-border-radius-base` in v4 

### ISSUE THREAD

**Issue by davehannon** [flexion/hud-disaster-data#77]
Issue opened with imdone.io from code comment on [6444247](https://github.com/flexion/hud-disaster-data/commit/64442473d97a502dc4e1349fdedc41f19a04133e)

TODO  Rename `$input-border-radius` to `$input-border-radius-base` in v4 id:4

----

https://github.com/flexion/hud-disaster-data/blob/64442473d97a502dc4e1349fdedc41f19a04133e/app/public/assets/_scss/01-vendors/bootstrap/_variables.scss#L199-L204

**Comment by piascikj** [comment]
In dependency
