### ISSUE TITLE
 parse values into flex-direction/flex-wrap 

### ISSUE THREAD

**Issue by davehannon** [flexion/hud-disaster-data#79]
Issue opened with imdone.io from code comment on [6444247](https://github.com/flexion/hud-disaster-data/commit/64442473d97a502dc4e1349fdedc41f19a04133e)

TODO  parse values into flex-direction/flex-wrap id:6

----

https://github.com/flexion/hud-disaster-data/blob/64442473d97a502dc4e1349fdedc41f19a04133e/app/public/assets/_scss/01-vendors/bourbon/css3/_flex-box.scss#L160-L165

**Comment by piascikj** [comment]
In dependency
